In [1]:
import numpy as np

In [22]:
l = [1,2,3,4,5,6]

In [27]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [30]:
l1 = [1,2,3,4,5,6,'ma']

In [40]:
np.array(l1)    #if any int value will be there so by defualt numpy connvert all into strings 

array(['1', '2', '3', '4', '5', '6', 'ma'], dtype='<U11')

In [41]:
l3 = [1,2,3,4,5,6,[2,5,8,6]]

In [39]:
np.array(l3)

C:\Users\Manoj\AppData\Local\Temp/ipykernel_19940/2976735194.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(l3)


array([1, 2, 3, 4, 5, 6, list([2, 5, 8, 6])], dtype=object)

In [32]:
l2 = [4,5,6,7,'sudh',34,565,True]

In [33]:
a1 =np.array(l2)  #by defualt numpy connvert all into strings 

In [42]:
a1

array(['4', '5', '6', '7', 'sudh', '34', '565', 'True'], dtype='<U11')

In [47]:
a1.ndim #dimension

1

In [51]:
len(a1)

8

In [22]:
a1.size  #no. of element

8

In [27]:
a1.shape  #matrix raw coloumn  

(8,)

In [162]:
a2 = np.array([[1,2,3],[4,5,6]])

In [23]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a2.ndim

2

In [28]:
a2.size

6

In [29]:
a2.shape   #2 raw and 3 colomn

(2, 3)

In [136]:
a3 = np.array([[[1,3,2],[4,5,6],[8,6,9]]])

In [18]:
a3

array([[[1, 3, 2],
        [4, 5, 6],
        [8, 6, 9]]])

In [19]:
a3.ndim    #dimenstion

3

In [26]:
a3.size

9

In [30]:
a3.shape   # 1 matrix and 3 raw 3 coloumns

(1, 3, 3)

In [ ]:
#for single random generate data

In [57]:
np.random.randint(2,50)

45

In [55]:
#to generate specific data in matrix form

In [41]:
np.random.randint(2,50,(3,4))

array([[42, 28, 16, 44],
       [27, 16, 26,  3],
       [ 8, 37, 10, 18]])

In [42]:
np.random.randint(2,50,(2,3,4))

array([[[41, 41, 23, 19],
        [43, 27, 32, 18],
        [42, 23,  4, 26]],

       [[21, 20, 33, 31],
        [22, 20, 37,  5],
        [ 4, 33, 13, 26]]])

In [45]:
np.random.randint(2,50,(4))

array([41,  2, 10,  5])

In [59]:
#(2,2,4,2,2)    #in bracket only last two digits are mean to as raws and coloumns and befor that
                #any digits will be mulptilied together and give result as no. of matrixs result 

In [61]:
np.random.randint(2,50,(2,2,4,2,2))

array([[[[[24, 26],
          [24, 47]],

         [[40,  2],
          [12, 19]],

         [[17, 37],
          [48, 33]],

         [[ 5, 21],
          [38, 31]]],


        [[[41, 29],
          [44, 13]],

         [[16, 10],
          [15, 22]],

         [[23, 38],
          [30, 14]],

         [[21, 35],
          [21,  3]]]],



       [[[[42, 13],
          [18, 33]],

         [[37, 39],
          [14, 27]],

         [[30, 40],
          [37, 25]],

         [[22, 26],
          [36, 16]]],


        [[[16, 44],
          [39, 29]],

         [[32, 41],
          [19, 27]],

         [[ 7, 34],
          [18, 38]],

         [[ 8, 10],
          [28, 20]]]]])

In [110]:
np.random.randint(10)

7

In [106]:
np.random.randint(10,20)

11

In [95]:
np.random.randint(10,20,5) #or     here 5 means coloumns

array([16, 10, 12, 18, 19])

In [99]:
np.random.randint(10,20,(5))

array([10, 16, 19, 10, 11])

In [100]:
np.random.randint(10,20,(5,5))   #here first 5 means raw and next 5 means column

array([[15, 11, 10, 14, 11],
       [10, 15, 13, 14, 11],
       [18, 10, 10, 18, 16],
       [17, 13, 18, 15, 18],
       [10, 11, 14, 12, 13]])

In [98]:
np.random.randint(10,20,(5,5,5))  #here first 5 means no. of matrix and next 5 means raw and next 5 means column

array([[[12, 12, 11, 12, 16],
        [13, 13, 16, 11, 10],
        [16, 15, 10, 18, 14],
        [13, 10, 10, 12, 10],
        [13, 12, 18, 13, 12]],

       [[10, 17, 13, 14, 12],
        [12, 17, 10, 14, 16],
        [19, 16, 18, 14, 13],
        [18, 10, 19, 10, 14],
        [19, 10, 17, 16, 15]],

       [[14, 13, 11, 13, 10],
        [10, 17, 17, 11, 14],
        [18, 13, 18, 14, 15],
        [19, 18, 19, 19, 19],
        [12, 13, 15, 16, 16]],

       [[18, 19, 15, 10, 15],
        [11, 17, 13, 10, 17],
        [19, 17, 15, 16, 19],
        [16, 17, 11, 12, 11],
        [14, 15, 13, 13, 17]],

       [[12, 13, 17, 13, 18],
        [11, 17, 14, 15, 11],
        [17, 17, 10, 13, 10],
        [18, 15, 17, 17, 15],
        [16, 17, 16, 17, 10]]])

In [75]:
#only random data by rand function

In [129]:
np.random.rand(3,4)  #here first no. is raw and second is column 
                     #and given random values

array([[0.6464221 , 0.12682264, 0.72663483, 0.59260886],
       [0.0671104 , 0.57819701, 0.37075784, 0.23699657],
       [0.71968589, 0.87435893, 0.35764428, 0.93759128]])

In [126]:
a4 = np.random.rand(4,4)

In [134]:
a4

array([[0.64096812, 0.58040153, 0.03755917, 0.24531511],
       [0.60230284, 0.78167694, 0.45724413, 0.38263444],
       [0.64526558, 0.83623831, 0.05188648, 0.01661015],
       [0.85780442, 0.14626164, 0.32733577, 0.79306589]])

In [ ]:
#for reshape fucntion only use factorial of original value, in a4 there are 16 values so probabilty will be
  (1,16),(16,1),(2,8),(8,2),(4,4)

In [ ]:
#reshape use to changed dimension

In [132]:
a4.reshape(2,8)

array([[0.64096812, 0.58040153, 0.03755917, 0.24531511, 0.60230284,
        0.78167694, 0.45724413, 0.38263444],
       [0.64526558, 0.83623831, 0.05188648, 0.01661015, 0.85780442,
        0.14626164, 0.32733577, 0.79306589]])

In [81]:
a4.reshape(8,2)

array([[0.23203359, 0.48586868],
       [0.46216478, 0.10456589],
       [0.13481763, 0.51030455],
       [0.50630823, 0.23517117],
       [0.61461097, 0.05353765],
       [0.21026462, 0.14546088],
       [0.83311052, 0.8783618 ],
       [0.8777713 , 0.03403487]])

In [82]:
a4.reshape(1,16)

array([[0.23203359, 0.48586868, 0.46216478, 0.10456589, 0.13481763,
        0.51030455, 0.50630823, 0.23517117, 0.61461097, 0.05353765,
        0.21026462, 0.14546088, 0.83311052, 0.8783618 , 0.8777713 ,
        0.03403487]])

In [83]:
a4.reshape(16,1)

array([[0.23203359],
       [0.48586868],
       [0.46216478],
       [0.10456589],
       [0.13481763],
       [0.51030455],
       [0.50630823],
       [0.23517117],
       [0.61461097],
       [0.05353765],
       [0.21026462],
       [0.14546088],
       [0.83311052],
       [0.8783618 ],
       [0.8777713 ],
       [0.03403487]])

In [84]:
a4.reshape(4,4)

array([[0.23203359, 0.48586868, 0.46216478, 0.10456589],
       [0.13481763, 0.51030455, 0.50630823, 0.23517117],
       [0.61461097, 0.05353765, 0.21026462, 0.14546088],
       [0.83311052, 0.8783618 , 0.8777713 , 0.03403487]])

In [90]:
a4.reshape(2,-1)

array([[0.23203359, 0.48586868, 0.46216478, 0.10456589, 0.13481763,
        0.51030455, 0.50630823, 0.23517117],
       [0.61461097, 0.05353765, 0.21026462, 0.14546088, 0.83311052,
        0.8783618 , 0.8777713 , 0.03403487]])

In [91]:
a4.reshape(2,2,4)

array([[[0.23203359, 0.48586868, 0.46216478, 0.10456589],
        [0.13481763, 0.51030455, 0.50630823, 0.23517117]],

       [[0.61461097, 0.05353765, 0.21026462, 0.14546088],
        [0.83311052, 0.8783618 , 0.8777713 , 0.03403487]]])

In [92]:
a4.reshape(1,1,1,1,1,1,2,2,4)

array([[[[[[[[[0.23203359, 0.48586868, 0.46216478, 0.10456589],
              [0.13481763, 0.51030455, 0.50630823, 0.23517117]],

             [[0.61461097, 0.05353765, 0.21026462, 0.14546088],
              [0.83311052, 0.8783618 , 0.8777713 , 0.03403487]]]]]]]]])

In [ ]:
#extract data from array or slicing operation

In [93]:
a1

array(['4', '5', '6', '7', 'sudh', '34', '565', 'True'], dtype='<U11')

In [94]:
a1[0]

'4'

In [95]:
a1[2:6]

array(['6', '7', 'sudh', '34'], dtype='<U11')

In [96]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U11')

In [97]:
a1[::-1]  #reverse

array(['True', '565', '34', 'sudh', '7', '6', '5', '4'], dtype='<U11')

In [137]:
a3

array([[[1, 3, 2],
        [4, 5, 6],
        [8, 6, 9]]])

In [145]:
a3[0]

array([[1, 3, 2],
       [4, 5, 6],
       [8, 6, 9]])

In [160]:
a3[0][0]

array([1, 3, 2])

In [151]:
a3[0][0][0]

1

In [153]:
a3[0][0][1]

3

In [155]:
a3[0][1]

array([4, 5, 6])

In [157]:
a3[0][2]

array([8, 6, 9])

In [158]:
a3[0][2][2]

9

In [99]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
a2[0]

array([1, 2, 3])

In [168]:
a2[1]

array([4, 5, 6])

In [165]:
a2[:1:]

array([[1, 2, 3]])

In [170]:
a2[:,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [172]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [106]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [109]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [119]:
a5 = np.random.randint(2,90,(6,5))

In [120]:
a5

array([[13, 83, 22, 20, 31],
       [46, 85, 24, 75, 62],
       [16, 27, 34, 32, 82],
       [78, 48,  3, 42, 15],
       [41,  8, 46,  8, 81],
       [ 8, 62,  3,  5, 79]])

In [121]:
a5[a5>40]  #find the greater than value

array([83, 46, 85, 75, 62, 82, 78, 48, 42, 41, 46, 81, 62, 79])

In [122]:
a5

array([[13, 83, 22, 20, 31],
       [46, 85, 24, 75, 62],
       [16, 27, 34, 32, 82],
       [78, 48,  3, 42, 15],
       [41,  8, 46,  8, 81],
       [ 8, 62,  3,  5, 79]])

In [123]:
a5[0,1]

83

In [124]:
a5[0,1] = 100  #change the value  

In [126]:
a5[0,1]

100

In [127]:
a5

array([[ 13, 100,  22,  20,  31],
       [ 46,  85,  24,  75,  62],
       [ 16,  27,  34,  32,  82],
       [ 78,  48,   3,  42,  15],
       [ 41,   8,  46,   8,  81],
       [  8,  62,   3,   5,  79]])

In [133]:
a6 = np.random.randint(0,3,(3,3))

In [134]:
a7 = np.random.randint(0,3,(3,3))

In [135]:
a6

array([[0, 0, 1],
       [0, 2, 2],
       [0, 1, 1]])

In [136]:
a7

array([[1, 0, 1],
       [1, 1, 2],
       [1, 0, 1]])

In [138]:
a6*a7  #simply mupltiplication

array([[0, 0, 1],
       [0, 2, 4],
       [0, 0, 1]])

In [ ]:
#matrix mupltiplication

In [139]:
a6@a7

array([[1, 0, 1],
       [4, 2, 6],
       [2, 1, 3]])

In [140]:
a6+100   #add

array([[100, 100, 101],
       [100, 102, 102],
       [100, 101, 101]])

In [141]:
a6*2  #mupltiply by no.

array([[0, 0, 2],
       [0, 4, 4],
       [0, 2, 2]])

In [142]:
a6/0

C:\Users\Manoj\AppData\Local\Temp/ipykernel_6896/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Manoj\AppData\Local\Temp/ipykernel_6896/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, inf],
       [nan, inf, inf],
       [nan, inf, inf]])

In [143]:
a6**3

array([[0, 0, 1],
       [0, 8, 8],
       [0, 1, 1]], dtype=int32)

In [145]:
a8 = np.zeros((4,4))  #if want all element as zero

In [146]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
a9 = np.ones((4,5))

In [149]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [160]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [ ]:
#broadcasting operation raw wise

In [151]:
a9+np.array([1,2,3,4,5])  #give raw wise additional operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [159]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [173]:
#broadcasting operation coloumn wise

In [174]:
np.array([[1,2,3,4]]).T               #transpose

array([[1],
       [2],
       [3],
       [4]])

In [154]:
np.array([[1,2,3,4]]).T + a9  #coloumn wise additional
                              #T means to transport and use when add coloumn wise

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [155]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [157]:
a6

array([[0, 0, 1],
       [0, 2, 2],
       [0, 1, 1]])

In [158]:
a6.T

array([[0, 0, 0],
       [0, 2, 1],
       [1, 2, 1]])

In [162]:
a5

array([[ 13, 100,  22,  20,  31],
       [ 46,  85,  24,  75,  62],
       [ 16,  27,  34,  32,  82],
       [ 78,  48,   3,  42,  15],
       [ 41,   8,  46,   8,  81],
       [  8,  62,   3,   5,  79]])

In [181]:
np.random.rand(5,4)

array([[0.34817408, 0.55487524, 0.58516135, 0.01856163],
       [0.8628719 , 0.94116505, 0.5003966 , 0.18386933],
       [0.39558715, 0.26063691, 0.39209977, 0.32525353],
       [0.67116855, 0.6254754 , 0.71256394, 0.70767747],
       [0.8317416 , 0.60579237, 0.17749541, 0.09320253]])

In [163]:
np.sqrt(a5)

array([[ 3.60555128, 10.        ,  4.69041576,  4.47213595,  5.56776436],
       [ 6.78232998,  9.21954446,  4.89897949,  8.66025404,  7.87400787],
       [ 4.        ,  5.19615242,  5.83095189,  5.65685425,  9.05538514],
       [ 8.83176087,  6.92820323,  1.73205081,  6.4807407 ,  3.87298335],
       [ 6.40312424,  2.82842712,  6.78232998,  2.82842712,  9.        ],
       [ 2.82842712,  7.87400787,  1.73205081,  2.23606798,  8.88819442]])

In [164]:
np.exp(a5)

array([[4.42413392e+05, 2.68811714e+43, 3.58491285e+09, 4.85165195e+08,
        2.90488497e+13],
       [9.49611942e+19, 8.22301271e+36, 2.64891221e+10, 3.73324200e+32,
        8.43835667e+26],
       [8.88611052e+06, 5.32048241e+11, 5.83461743e+14, 7.89629602e+13,
        4.09399696e+35],
       [7.49841700e+33, 7.01673591e+20, 2.00855369e+01, 1.73927494e+18,
        3.26901737e+06],
       [6.39843494e+17, 2.98095799e+03, 9.49611942e+19, 2.98095799e+03,
        1.50609731e+35],
       [2.98095799e+03, 8.43835667e+26, 2.00855369e+01, 1.48413159e+02,
        2.03828107e+34]])

In [165]:
np.log10(a5)

array([[1.11394335, 2.        , 1.34242268, 1.30103   , 1.49136169],
       [1.66275783, 1.92941893, 1.38021124, 1.87506126, 1.79239169],
       [1.20411998, 1.43136376, 1.53147892, 1.50514998, 1.91381385],
       [1.8920946 , 1.68124124, 0.47712125, 1.62324929, 1.17609126],
       [1.61278386, 0.90308999, 1.66275783, 0.90308999, 1.90848502],
       [0.90308999, 1.79239169, 0.47712125, 0.69897   , 1.89762709]])

In [168]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [83]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [ ]:
#no. of value create using linspace

In [185]:
np.linspace(2,10,num=20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [10]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [11]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [ ]:
#identity matrix(raw and coloumn are equal and diagnosis value will be same)

In [12]:
np.eye(5)  #by defualt give 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#data visualization liabary 
#matplot
#seaborn
#plotlick
#pandas plot
#cufflinks

In [186]:
#!pip install cufflinks  (cufflinks need to install everytime)

In [23]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [24]:
cf.go_offline()

In [25]:
np.random.randn(100,3)

array([[ 0.42643114, -1.10249616,  0.47700899],
       [-0.16371551,  0.10729937, -0.29779406],
       [ 0.76932064,  0.26758642,  0.80820175],
       [ 0.18069157, -0.52883168, -0.83517693],
       [-0.69992653,  0.04068048, -0.65504834],
       [ 1.21006294, -0.87223227, -0.90981606],
       [-1.86674594,  0.16509135, -0.70869788],
       [-1.52573855,  1.41570254, -0.43001732],
       [-1.51834876,  0.14913259,  0.77207251],
       [-0.91073751, -2.15222532,  1.46607004],
       [-0.11911994, -1.48560973, -1.94380604],
       [-0.84522996, -0.31360406, -0.97916255],
       [-0.86670081, -0.61625364,  0.50781784],
       [-1.93865634,  0.89450108,  1.38735622],
       [-0.46966927,  1.05988343, -0.20855674],
       [ 1.46325088, -0.90942429, -0.2180348 ],
       [ 0.89454682, -0.34414565,  0.36121804],
       [-2.5078417 ,  0.77024268,  0.80850375],
       [-1.79165064,  0.05434631,  0.0913915 ],
       [-0.36713047,  0.53861846, -0.08272001],
       [ 0.45490112,  0.66868057,  0.837

In [26]:
#convert data into pandas data frame

In [27]:
df = pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [28]:
df

A         B         C
0   0.195292  0.064715 -0.372521
1   0.109472 -1.380491 -0.134882
2  -0.140662  0.405283 -0.718789
3  -1.166050 -1.094677  0.448574
4  -0.832165 -1.951225 -0.616938
..       ...       ...       ...
95 -0.997743  2.232328 -0.529352
96  0.958890 -1.581354 -0.484010
97 -1.930928 -0.838882 -0.836995
98 -0.747251 -0.131199 -0.486767
99 -0.056332 -1.081032  0.292930

[100 rows x 3 columns]

In [29]:
#graph useing cufflinks

In [7]:
df.iplot()

In [8]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [9]:
df1

0
0   20
1   86
2   90
3   60
4   14
..  ..
95  37
96  54
97  10
98  82
99  58

[100 rows x 1 columns]

In [10]:
df1.iplot()

In [47]:
    df

A         B         C
0   1.290667  2.029123 -0.385854
1  -1.640314  0.129316 -0.516185
2  -0.425887  1.365962 -0.560995
3   0.253072 -0.688838  0.183600
4  -1.359464  1.329170 -1.302267
..       ...       ...       ...
95 -1.276168  0.783064  1.140345
96 -0.071635 -1.029832  0.643524
97  0.173342 -1.827355 -0.775384
98 -0.443381 -1.124099 -0.158231
99  0.414641 -1.549946  1.871439

[100 rows x 3 columns]

In [48]:
#comparison between coloumn

In [11]:
df.iplot(x='A',y='B')

In [ ]:
#changed mode of graph

In [12]:
df.iplot(x='A',y='B',mode='markers')

In [13]:
df.iplot(mode='markers')

In [212]:
#plot graph using seaborn

In [15]:
df2 = sns.load_dataset('titanic')  #titaninc data is by defualt data

In [16]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [17]:
df2.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [18]:
#find the relation between age and fare

In [19]:
df2.iplot(x='age',y='fare',mode='markers')

In [ ]:
#find the relation between age and pclass

In [20]:
df2.iplot(x='age',y='pclass',mode='markers')

In [ ]:
#find the relation between fare and pclass

In [21]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [93]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [ ]:
#who is survived more male or female

In [22]:
df2.iplot(kind='bar',x='sex', y='survived',)